#!/usr/bin/env python3
"""Renders status.json into a static docs/index.html dashboard for GitHub Pages."""

import json
from datetime import datetime
from pathlib import Path

STATUS_FILE = Path("status.json")
OUT_FILE = Path("docs/index.html")

STATE_LABELS = {
    "changed": ("Changed", "#C9862A"),
    "unchanged": ("No change", "#2E7D46"),
    "baseline": ("Baseline saved", "#5B7A99"),
    "error": ("Error", "#B3261E"),
    "ok": ("Pending", "#888"),
}


def fmt(dt_str):
    if not dt_str:
        return "—"
    try:
        dt = datetime.fromisoformat(dt_str)
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return dt_str


def main():
    Path("docs").mkdir(exist_ok=True)

    if not STATUS_FILE.exists():
        rows_html = "<tr><td colspan='5'>No status data yet. Run the checker first.</td></tr>"
        generated_at = "—"
    else:
        data = json.loads(STATUS_FILE.read_text())
        generated_at = fmt(data.get("generated_at"))
        rows = []
        for site in data.get("sites", []):
            label, color = STATE_LABELS.get(site["state"], ("Unknown", "#888"))
            error_note = f"<div class='err'>{site['error']}</div>" if site.get("error") else ""
            rows.append(f"""
            <tr>
              <td><a href="{site['url']}" target="_blank" rel="noopener">{site['name']}</a>
                  <div class="notes">{site.get('notes','')}</div>{error_note}</td>
              <td><span class="badge" style="background:{color}">{label}</span></td>
              <td>{fmt(site.get('last_checked'))}</td>
              <td>{fmt(site.get('last_changed'))}</td>
              <td class="url"><a href="{site['url']}" target="_blank" rel="noopener">{site['url']}</a></td>
            </tr>""")
        rows_html = "\n".join(rows) if rows else "<tr><td colspan='5'>No sites configured.</td></tr>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Website Watcher Dashboard</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          background: #f7f7f5; color: #1a1a1a; margin: 0; padding: 40px 20px; }}
  .wrap {{ max-width: 900px; margin: 0 auto; }}
  h1 {{ font-size: 1.5rem; margin-bottom: 4px; }}
  .sub {{ color: #666; margin-bottom: 28px; font-size: 0.9rem; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff;
           border: 1px solid #e2e2e0; border-radius: 8px; overflow: hidden; }}
  th, td {{ text-align: left; padding: 12px 14px; border-bottom: 1px solid #eee;
            vertical-align: top; font-size: 0.9rem; }}
  th {{ background: #fafaf9; font-weight: 600; color: #444; }}
  tr:last-child td {{ border-bottom: none; }}
  a {{ color: #4A6FA5; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .badge {{ color: #fff; padding: 3px 10px; border-radius: 999px; font-size: 0.78rem;
            font-weight: 600; white-space: nowrap; }}
  .notes {{ color: #888; font-size: 0.8rem; margin-top: 3px; }}
  .err {{ color: #B3261E; font-size: 0.8rem; margin-top: 3px; }}
  .url {{ max-width: 220px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
  footer {{ margin-top: 20px; color: #999; font-size: 0.8rem; text-align: center; }}
</style>
</head>
<body>
<div class="wrap">
  <h1>Website Watcher</h1>
  <div class="sub">Last run: {generated_at}</div>
  <table>
    <thead>
      <tr><th>Site</th><th>Status</th><th>Last checked</th><th>Last changed</th><th>URL</th></tr>
    </thead>
    <tbody>
      {rows_html}
    </tbody>
  </table>
  <footer>Auto-generated by GitHub Actions &middot; runs daily</footer>
</div>
</body>
</html>
"""
    OUT_FILE.write_text(html)
    print(f"Wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
